apiVersion: v1                # General
kind: Service                 # General

metadata:                     # Service metadata
  name: flask-mongo-service
  namespace: app-ns

spec:                         # Service specification
  type: NodePort

  selector:                   # Which Pods receive traffic
    app: flask-mongo-app

  ports:                      # Network configuration
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
