apiVersion: v1
kind: Service

metadata:
  name: mongo-service
  namespace: app-ns
  labels:
    app: mongo

spec:
  selector:
    app: mongo

  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

  # Default type.
  # Accessible only inside the cluster.
  type: ClusterIP
