# This Pipeline can be use only when we have a self-host runner with tag "dev-runner". 
# Most of the Stages are executed on Private Runner and few are on Gitlab-Public Runner 

# ----------------------------------------------------------------------
#                     HOW TO USE IT
# Just copy the Content and put in .gitlab-ci.yml file inside gitlab Repo and you will be good to go. 
#---------------------------------------------------------------------

stages:
  - install_dependencies  # This stage is useful when we have our own runner and we want to install packeages. on Public runner we can make use of built-in services/images 
  - secret_scan
  - security_scan
  - docker_build
  - trivy_image_scan 
  - docker_push 
  - update_manifests
  - deploy-to-ec2

variables:
  IMAGE: "ai-sre-agent"
 

install_dependencies:
  stage: install_dependencies
  tags:
    - dev-runner

  script:
    # 1. Check / install Gitleaks
    - |
      if command -v gitleaks >/dev/null 2>&1; then
        echo "Gitleaks already installed: $(gitleaks version)"
      else
        echo "Gitleaks not found. Installing..."
        curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/scripts/install.sh | sh -s -- -b /usr/local/bin
        echo "Gitleaks installed: $(gitleaks version)"
      fi 

    # 2. Check / install Docker
    - |
      if command -v docker >/dev/null 2>&1; then
        echo "Docker already installed: $(docker --version)"
      else
        echo "Docker not found. Installing..."
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl enable --now docker
        sudo usermod -aG docker $USER && newgrp docker
        sudo chmod 666 /var/run/docker.sock
        sudo usermod -aG docker gitlab-runner && newgrp docker
        echo "Docker installed $(docker --version)"
      fi

    #3. Check / install Docker Compose
    - |
      if  command -v docker-compose >/dev/null 2>&1 >/dev/null 2>&1; then
        echo "Docker Compose already installed $(docker compose --version)"
      else
        echo "Docker Compose not found. Installing from repository script..."

        chmod +x instal_docker-compose.sh
        ./instal_docker-compose.sh

        echo "Docker Compose installed:"
        echo docker compose version
      fi
  tags:
    - dev-runner
 
 
secret_scan:  
  stage: secret_scan
  script:
    - gitleaks version
    - gitleaks detect --source . --verbose --redact
  tags:
    - dev-runner

trivy_fs:
  stage: security_scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs --scanners vuln,secret .
    
docker_build:
  stage: docker_build
  script:
    - whoami
    - cd DkrFiles
    - docker build -t $DOCKER_HUB_USERNAME/$IMAGE:CI_PIPELINE_IID . 
    # Verify
    - docker save $DOCKER_HUB_USERNAME/$IMAGE:CI_PIPELINE_IID -o image.tar

    - mv image.tar ../image.tar
    - sudo ls -lh ../image.tar

  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour
  tags:
    - dev-runner

trivy_image_scan:
  stage: trivy_image_scan

  image:
    name: aquasec/trivy:latest
    entrypoint: [""]

  script:
    - echo "Scanning Docker image artifact..."
    - echo "The 0 is Set Just for Passing the Test. Although the Code has some Vulnerabilites causing to Fail"
    - trivy image --input image.tar --severity HIGH,CRITICAL --exit-code 0 --no-progress
    
docker_push:
  stage: docker_push
  script:
    - docker images
    - echo "DockerHub Username is $DOCKER_HUB_USERNAME"
    - echo "$DOCKER_HUB_PASSWD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker push "$DOCKER_HUB_USERNAME/$IMAGE:CI_PIPELINE_IID" 

  tags:  
   - dev-runner
  
 
update-docker-compose-yml:
  stage: update_manifests

  image: alpine:latest

  # before_script:
  #   - apk add --no-cache git

  script:
    # Clone the existing GitHub repository
    - git clone https://${MANIFEST_USER}:${MANIFEST_TOKEN}@github.com/OzairKhan1/Kubernetes-ManifestFiles.git

    # Enter the cloned repository
    - cd Kubernetes-ManifestFiles

    # Update the Docker image tag
    - |
      sed -i "s#image: ${DOCKER_HUB_USERNAME}/${IMAGE}:.*#image: ${DOCKER_HUB_USERNAME}/${IMAGE}:gitlab.${CI_PIPELINE_IID}#g" \
      AegisOps_AI_SRE_Agen/docker-compose.yml

    # Configure Git
    - git config user.name "GitLab CI"
    - git config user.email "gitlab-ci@example.com"

    # Commit the change
    - git add AegisOps_AI_SRE_Agen/docker-compose.yml
    - git commit -m "Update image to gitlab.${CI_PIPELINE_IID}" || echo "No changes to commit"

    # Push back to GitHub main
    - git push origin main

    - echo "The GitHub repository was successfully updated!"

  tags:
    - dev-runner

deploy-to-ec2:
  stage: deploy-to-ec2
  script:
    - echo "Deploying to Server"
    - docker compose up -d 
  tags:
    - dev-runner
